/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#15121b',
        'surface-dim': '#15121b',
        'surface-bright': '#3b3742',
        'surface-container-lowest': '#0f0d15',
        'surface-container-low': '#1d1a23',
        'surface-container': '#211e27',
        'surface-container-high': '#2c2832',
        'surface-container-highest': '#37333d',
        'on-surface': '#e7e0ed',
        'on-surface-variant': '#cbc3d7',
        'inverse-surface': '#e7e0ed',
        'inverse-on-surface': '#322f39',
        'outline': '#958ea0',
        'outline-variant': '#494454',
        'surface-tint': '#d0bcff',
        'surface-variant': '#37333d',
        'primary': '#d0bcff',
        'on-primary': '#3c0091',
        'primary-container': '#a078ff',
        'on-primary-container': '#340080',
        'inverse-primary': '#6d3bd7',
        'primary-fixed': '#e9ddff',
        'primary-fixed-dim': '#d0bcff',
        'on-primary-fixed': '#23005c',
        'on-primary-fixed-variant': '#5516be',
        'secondary': '#adc6ff',
        'on-secondary': '#002e6a',
        'secondary-container': '#0566d9',
        'on-secondary-container': '#e6ecff',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary-fixed': '#001a42',
        'on-secondary-fixed-variant': '#004395',
        'tertiary': '#4cd7f6',
        'on-tertiary': '#003640',
        'tertiary-container': '#009eb9',
        'on-tertiary-container': '#002f38',
        'tertiary-fixed': '#acedff',
        'tertiary-fixed-dim': '#4cd7f6',
        'on-tertiary-fixed': '#001f26',
        'on-tertiary-fixed-variant': '#004e5c',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#15121b',
        'on-background': '#e7e0ed',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        'container-max': '1280px',
        gutter: '24px',
      },
      fontFamily: {
        'display': ['Plus Jakarta Sans', 'sans-serif'],
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
