import { NavLink } from 'react-router-dom';

export default function Home() {
  return (
    <main className="flex-grow flex flex-col pt-[100px] max-w-container-max mx-auto w-full px-md md:px-lg pb-xl">
      {/* Hero Section */}
      <section className="flex flex-col items-center text-center mt-xl mb-xl fade-in">
        <h1 className="font-display text-display-lg-mobile md:text-display-lg text-transparent bg-clip-text bg-gradient-to-r from-primary via-primary-fixed to-secondary mb-md">
          DevPath AI
        </h1>
        <p className="font-body text-body-lg text-on-surface-variant max-w-3xl mb-lg">
          Shape your future with data. Analyze industry trends, discover the best tech field for you, and reach your career goals with AI-powered guidance.
        </p>
        <div className="flex flex-col sm:flex-row gap-sm">
          <NavLink
            to="/predict"
            className="font-label text-label-md bg-gradient-to-r from-primary to-secondary text-on-primary px-lg py-sm rounded-lg glow-button transition-all font-bold text-center"
          >
            Get Started
          </NavLink>
          <NavLink
            to="/quiz"
            className="font-label text-label-md glass-panel text-on-surface px-lg py-sm rounded-lg hover:bg-white/10 transition-all border border-white/10 text-center"
          >
            Career Quiz
          </NavLink>
        </div>
      </section>

      {/* Features Bento Grid */}
      <section className="mb-xl fade-in">
        <h2 className="font-headline text-headline-lg text-on-surface mb-lg text-center">
          Key Features
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-md">
          {/* Salary Prediction */}
          <div className="glass-panel p-md rounded-xl flex flex-col h-full hover:-translate-y-1 transition-transform duration-300">
            <div className="w-12 h-12 rounded-lg bg-primary/20 flex items-center justify-center mb-md border border-primary/30">
              <span
                className="material-symbols-outlined text-primary text-[28px]"
                style={{ fontVariationSettings: "'FILL' 1" }}
              >
                payments
              </span>
            </div>
            <h3 className="font-headline text-headline-md text-on-surface mb-xs">
              Salary Prediction
            </h3>
            <p className="font-body text-body-md text-on-surface-variant flex-grow">
              Calculate your potential salary based on your experience, tech stack, and location using up-to-date market data.
            </p>
            <div className="mt-md">
              <span className="inline-block px-xs py-base rounded-full bg-tertiary/10 text-tertiary font-label text-label-sm">
                Data-Driven
              </span>
            </div>
          </div>

          {/* Career Quiz */}
          <div className="glass-panel p-md rounded-xl flex flex-col h-full hover:-translate-y-1 transition-transform duration-300">
            <div className="w-12 h-12 rounded-lg bg-secondary/20 flex items-center justify-center mb-md border border-secondary/30">
              <span
                className="material-symbols-outlined text-secondary text-[28px]"
                style={{ fontVariationSettings: "'FILL' 1" }}
              >
                assignment
              </span>
            </div>
            <h3 className="font-headline text-headline-md text-on-surface mb-xs">
              Career Quiz
            </h3>
            <p className="font-body text-body-md text-on-surface-variant flex-grow">
              Discover the most suitable software field for you (Frontend, Backend, Data, etc.) with our comprehensive survey analyzing your interests and skills.
            </p>
            <div className="mt-md">
              <span className="inline-block px-xs py-base rounded-full bg-tertiary/10 text-tertiary font-label text-label-sm">
                Personalized
              </span>
            </div>
          </div>

          {/* AI-Powered Analysis */}
          <div className="glass-panel p-md rounded-xl flex flex-col h-full hover:-translate-y-1 transition-transform duration-300">
            <div className="w-12 h-12 rounded-lg bg-tertiary/20 flex items-center justify-center mb-md border border-tertiary/30">
              <span
                className="material-symbols-outlined text-tertiary text-[28px]"
                style={{ fontVariationSettings: "'FILL' 1" }}
              >
                psychology
              </span>
            </div>
            <h3 className="font-headline text-headline-md text-on-surface mb-xs">
              AI-Powered Analysis
            </h3>
            <p className="font-body text-body-md text-on-surface-variant flex-grow">
              Get custom learning paths and project recommendations generated by AI to specialize in your chosen field.
            </p>
            <div className="mt-md">
              <span className="inline-block px-xs py-base rounded-full bg-tertiary/10 text-tertiary font-label text-label-sm">
                Smart System
              </span>
            </div>
          </div>
        </div>
      </section>

      {/* Data Info Section */}
      <section className="glass-panel rounded-xl p-lg relative overflow-hidden fade-in">
        <div className="absolute right-0 top-0 w-64 h-64 bg-primary/10 rounded-full blur-[80px] -translate-y-1/2 translate-x-1/4" />
        <div className="relative z-10 flex flex-col md:flex-row items-center gap-lg">
          <div className="flex-1">
            <h2 className="font-headline text-headline-lg text-on-surface mb-sm">
              Reliable Data Sources
            </h2>
            <p className="font-body text-body-md text-on-surface-variant mb-md">
              Our predictions and analysis are based on the latest and most comprehensive{' '}
              <a 
                href="https://www.kaggle.com/datasets/edoardogalli/stack-overflow-annual-developer-survey-2025?resource=download&select=survey_results_public.csv"
                target="_blank"
                rel="noopener noreferrer"
                className="font-bold text-primary hover:underline hover:text-primary-fixed transition-colors"
              >
                Stack Overflow Developer Survey 2025
              </a>{' '}
              data, calculated using machine learning models. Don't leave your career decisions to chance with millions of data points updated annually.
            </p>
            <NavLink
              to="/predict"
              className="inline-flex items-center text-primary font-label text-label-md hover:text-primary-fixed transition-colors"
            >
              Explore Our Data Methodology
              <span className="material-symbols-outlined ml-base text-[18px]">
                arrow_forward
              </span>
            </NavLink>
          </div>
          <div className="w-full md:w-1/3 flex justify-center">
            <div className="w-32 h-32 rounded-full border-4 border-surface-variant flex items-center justify-center bg-surface-container-high relative shadow-[0_0_30px_rgba(208,188,255,0.15)]">
              <span
                className="material-symbols-outlined text-[48px] text-primary"
                style={{ fontVariationSettings: "'FILL' 1" }}
              >
                database
              </span>
              <div className="absolute -right-4 -top-4 bg-tertiary text-on-tertiary text-xs font-bold px-2 py-1 rounded-full">
                +100K Data
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
